# Generated by Django 5.2.17 on 2026-08-27 09:35

import common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR"),
                            ("pdf_compress", "PDF Compress"),
                            ("pdf_merge", "PDF Merge"),
                            ("ai_summary", "AI Summary"),
                            ("expense_extract", "Expense Extract"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ocr_jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "extracted_text_encrypted",
                    common.fields.EncryptedTextField(
                        aad_field="document_id", db_column="extracted_text"
                    ),
                ),
                ("detected_language", models.CharField(blank=True, max_length=20)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ocr_results",
                "managed": False,
            },
            bases=(common.fields.DecryptOnAccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                ("doc_type", models.CharField(blank=True, max_length=50)),
                ("data", models.JSONField(default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "extracted_data",
            },
        ),
    ]
