# Generated by Django 5.2.17 on 2026-08-27 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("page_number", models.IntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("freehand", "Freehand Drawing"),
                            ("text", "Text Label"),
                            ("rectangle", "Rectangle"),
                            ("circle", "Circle"),
                            ("arrow", "Arrow"),
                            ("highlight", "Highlight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("user_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "annotations",
            },
        ),
    ]
