# Generated by Django 6.1 on 2026-08-25 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("owner_id", models.UUIDField(db_index=True)),
                ("shared_with_id", models.UUIDField(blank=True, null=True)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("permission", models.CharField(default="view", max_length=20)),
                (
                    "share_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_shares",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro_monthly", "Pro Monthly"),
                            ("pro_yearly", "Pro Yearly"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
    ]
