# Generated by Django 6.1 on 2026-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_add_org_id_to_document_shares"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentshare",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(default="free", max_length=20),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
