# Generated by Django 5.2.17 on 2026-08-29 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0003_alter_documentshare_options_alter_subscription_plan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageEncryptionMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                ("wrapped_dek", models.BinaryField()),
                ("nonce", models.BinaryField()),
                ("key_id", models.CharField(max_length=255)),
                (
                    "original_content_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "storage_encryption_metadata",
            },
        ),
    ]
