# Generated by Django 5.2.17 on 2026-08-29 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("folder_id", models.UUIDField(blank=True, null=True)),
                ("title", models.TextField(default="Untitled scan")),
                ("doc_type", models.CharField(default="document", max_length=20)),
                ("page_count", models.IntegerField(default=1)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("original_storage_path", models.TextField(blank=True, null=True)),
                ("pdf_storage_path", models.TextField(blank=True, null=True)),
                ("is_searchable", models.BooleanField(default=False)),
                ("is_password_protected", models.BooleanField(default=False)),
                ("ocr_status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("owner_id", models.UUIDField(db_index=True)),
                ("shared_with_id", models.UUIDField(blank=True, null=True)),
                ("permission", models.CharField(default="view", max_length=10)),
                ("share_token", models.TextField(blank=True, null=True, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_shares",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField()),
                ("tag_id", models.UUIDField()),
            ],
            options={
                "db_table": "document_tags",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExpenseData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                ("vendor", models.TextField(blank=True, null=True)),
                ("expense_date", models.DateField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="NPR", max_length=3)),
            ],
            options={
                "db_table": "expense_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("color", models.CharField(default="#4CFFB5", max_length=7)),
                ("parent_folder_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "folders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("detected_language", models.TextField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ocr_results",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("page_number", models.IntegerField()),
                ("image_storage_path", models.TextField()),
                ("filter_applied", models.CharField(default="original", max_length=20)),
                ("brightness", models.IntegerField(default=0)),
                ("contrast", models.IntegerField(default=0)),
                ("rotation", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "pages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.TextField(blank=True, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                (
                    "preferred_ocr_lang",
                    models.CharField(default="ne+en", max_length=20),
                ),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("plan", models.CharField(default="free", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "profiles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True, unique=True)),
                ("plan", models.CharField(default="free", max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "subscriptions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "tags",
                "managed": False,
            },
        ),
    ]
