# Generated by Django 6.1 on 2026-08-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("auth.authenticated", "Authenticated"),
                            ("auth.token_invalid", "Invalid token presented"),
                            ("auth.token_expired", "Expired token presented"),
                            (
                                "auth.revoked_token_reuse_attempt",
                                "Revoked token reuse attempt",
                            ),
                            ("document.viewed", "Document viewed"),
                            ("document.downloaded", "Document downloaded"),
                            ("document.decrypted", "Document content decrypted"),
                            ("document.shared", "Document share created"),
                            ("document.deleted", "Document deleted"),
                            ("admin.accessed", "Admin panel accessed"),
                            ("admin.data_export", "Admin exported data"),
                            ("key.rotation", "Encryption key rotation performed"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("actor_role", models.CharField(default="unknown", max_length=32)),
                ("target_type", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "target_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "previous_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("entry_hash", models.CharField(editable=False, max_length=64)),
            ],
            options={
                "db_table": "audit_log_entries",
                "ordering": ["id"],
            },
        ),
    ]
