# Generated by Django 5.2.17 on 2026-08-29 10:16

import common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "vendor_encrypted",
                    common.fields.EncryptedTextField(
                        aad_field="document_id", db_column="vendor"
                    ),
                ),
                ("expense_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="NPR", max_length=3)),
            ],
            options={
                "db_table": "expense_data",
                "managed": False,
            },
            bases=(common.fields.DecryptOnAccessMixin, models.Model),
        ),
    ]
